PayAltcoins/Gourl/Controllers/GoUrl/ExamplesController.cs
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using Gourl.GoUrlCore;
using Gourl.Models;
using Gourl.Models.GoUrl;

namespace Gourl.Controllers.GoUrl
{
    public class ExamplesController : Controller
    {
        // GET: Examples
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Basic()
        {
            OptionsModel options = new OptionsModel()
            {
                public_key = "-your public key for Bitcoin box-",
                private_key = "-your private key for Bitcoin box-",
                webdev_key = "",
                orderID = "your_product1_or_signuppage1_etc",
                userID = "",
                userFormat = "COOKIE",
                amount = 0,
                amountUSD = 2,
                period = "24 HOUR",
                iframeID = "",
                language = "DE"
            };
            using (Cryptobox cryptobox = new Cryptobox(options))
            {
                DisplayCryptoboxModel model = cryptobox.GetDisplayCryptoboxModel();
                // A. Process Received Payment
                if (cryptobox.is_paid())
                {
                    ViewBag.Message = "A. User will see this message during 24 hours after payment has been made!" +
                                      "<br/>" + cryptobox.amount_paid() + " " + cryptobox.coin_label() +
                                      "  received<br/>";
                    // Your code here to handle a successful cryptocoin payment/captcha verification
                    // For example, give user 24 hour access to your member pages

                    // B. One-time Process Received Payment
                    if (!cryptobox.is_processed())
                    {
                        ViewBag.Message += "B. User will see this message one time after payment has been made!";
                        // Your code here - for example, publish order number for user
                        // ...

                        // Also you can use is_confirmed() - return true if payment confirmed 
                        // Average transaction confirmation time - 10-20min for 6 confirmations  

                        // Set Payment Status to Processed
                        cryptobox.set_status_processed();

                        // Optional, cryptobox_reset() will delete cookies/sessions with userID and 
                        // new cryptobox with new payment amount will be show after page reload.
                        // Cryptobox will recognize user as a new one with new generated userID
                        // cryptobox_reset(); 
                    }
                }
                ViewBag.Message = "The payment has not been made yet";

                return View(model);
            }
        }

        public ActionResult PayPerDownload()
        {

            ViewBag.filename = "my_file1.zip";
            string dir = "protected";
            OptionsModel options = new OptionsModel()
            {
                public_key = "-your public key for Bitcoin box-",
                private_key = "-your private key for Bitcoin box-",
                webdev_key = "",
                orderID = Calculator.md5(dir + ViewBag.filename),
                userID = "",
                userFormat = "COOKIE",
                amount = 0,
                amountUSD = (decimal)0.2,
                period = "24 HOUR",
                iframeID = "",
                language = "EN"
            };
            using (Cryptobox cryptobox = new Cryptobox(options))
            {
                if (cryptobox.is_paid())
                {
                    ViewBag.DownloadLink = "href = " + Url.Action("Download");
                    cryptobox.set_status_processed();
                }
                else
                {
                    ViewBag.DownloadLink = "onclick='alert(\"You need to send " + cryptobox.coin_name() +
                                           "s first !\")' href='#a'";
                }

                DisplayCryptoboxModel model = cryptobox.GetDisplayCryptoboxModel();

                return View(model);
            }
        }

        public FileResult Download()
        {
            string filename = "my_file1.zip";
            string dir = "protected";

            byte[] file = System.IO.File.ReadAllBytes(Server.MapPath(@"~/" + dir + "//" + filename));
            return File(file, System.Net.Mime.MediaTypeNames.Application.Octet, filename);
        }

        public ActionResult PayPerDownloadMulti()
        {
            ViewBag.filename = "my_file1.zip";
            string dir = "protected";

            string defPaiment = "bitcoin";

            string[] available_payments = new[] { "bitcoin", "dogecoin" };
            IDictionary<string, IDictionary<string, string>> all_keys = new Dictionary
                <string, IDictionary<string, string>>()
            {
                {
                    "bitcoin", new Dictionary<string, string>()
                    {
                        {"public_key", "-your public key for Bitcoin box-"},
                        {"private_key", "-your private key for Bitcoin box-"}
                    }
                },
                {
                    "dogecoin", new Dictionary<string, string>()
                    {
                        {"public_key", "-your public key for Dogecoin box-"},
                        {"private_key", "-your private key for Dogecoin box-"}
                    }
                }
            };

            foreach (KeyValuePair<string, IDictionary<string, string>> valuePair in all_keys)
            {
                if (valuePair.Value["public_key"] == null || valuePair.Value["private_key"] == null ||
                    valuePair.Value["public_key"] == "" || valuePair.Value["private_key"] == "")
                {
                    return
                        new ContentResult()
                        {
                            Content = "Please add your public/private keys for " + valuePair.Key +
                                      " in all_keys variable"
                        };
                }
                else if (!valuePair.Value["public_key"].Contains("PUB"))
                {
                    return
                        new ContentResult()
                        {
                            Content = "Invalid public key for " + valuePair.Key +
                                      " in all_keys variable"
                        };
                }
                else if (!valuePair.Value["private_key"].Contains("PRV"))
                {
                    return
                        new ContentResult()
                        {
                            Content = "Invalid private key for " + valuePair.Key +
                                      " in all_keys variable"
                        };
                }
                else if (!ConfigurationManager.AppSettings["PrivateKeys"].Contains(valuePair.Value["private_key"]))
                {
                    return
                        new ContentResult()
                        {
                            Content = "Please add your private key for " + valuePair.Key +
                                      " in Web.config."
                        };
                }
            }

            string coinName = CryptoHelper.cryptobox_selcoin(available_payments, defPaiment);
            OptionsModel options = new OptionsModel()
            {
                public_key = all_keys[coinName]["public_key"],
                private_key = all_keys[coinName]["private_key"],
                webdev_key = "",
                orderID = Calculator.md5(dir + ViewBag.filename),
                userID = "",
                userFormat = "COOKIE",
                amount = 0,
                amountUSD = (decimal)0.01,
                period = "24 HOUR",
                language = "en"
            };
            using (Cryptobox cryptobox = new Cryptobox(options))
            {
                if (cryptobox.is_paid())
                {
                    ViewBag.DownloadLink = "href = " + Url.Action("Download");
                    cryptobox.set_status_processed();
                }
                else
                {
                    ViewBag.DownloadLink = "onclick='alert(\"You need to send " + cryptobox.coin_name() +
                                           "s first !\")' href='#a'";
                }

                DisplayCryptoboxModel model = cryptobox.GetDisplayCryptoboxModel();
                ViewBag.Coins = available_payments;
                ViewBag.DefCoin = defPaiment;
                ViewBag.DefLang = options.language;

                return View(model);
            }
        }

        public ActionResult PayPerMembership()
        {
            OptionsModel options = new OptionsModel()
            {
                public_key = "-your public key for Bitcoin box-",
                private_key = "-your private key for Bitcoin box-",
                webdev_key = "",
                orderID = "premium_membership",
                userID = "",
                userFormat = "COOKIE",
                amount = 0,
                amountUSD = (decimal)0.2,
                period = "1 MONTH",
                language = "en"
            };

            using (Cryptobox cryptobox = new Cryptobox(options))
            {
                if (cryptobox.is_paid())
                {
                    if (!cryptobox.is_processed())
                    {
                        ViewBag.Message = "Thank you (order #" + options.orderID + ", payment #" +
                                          cryptobox.payment_id() + "). We upgraded your membership to Premium";
                        cryptobox.set_status_processed();
                    }
                    else
                    {

PayAltcoins/Gourl/Views/Examples/Basic.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Basic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Basic</h2>

<div style='font-size:12px;margin:50px 0 5px 370px'>Language: &#160; @Html.LanguageBox("en")</div>
@Html.Cryptobox(Model)
@Html.Raw(ViewBag.Message);

@*@Html.Partial("Partial/_Cryptobox", Model)*@

@*@Html.Action("Cryptobox","Gourl", new{ options = new OptionsModel()
    {
        public_key = "-your public key for Bitcoin box-",
        private_key = "-your private key for Bitcoin box-",
        webdev_key = "",
        orderID = "your_product1_or_signuppage1_etc",
        userID = "", //"72230eec70c4e5",
        userFormat = "COOKIE",
        amount = 0,
        amountUSD = 2,
        period = "24 HOUR",
        iframeID = "",
        language = "EN"
    }})*@

PayAltcoins/Gourl/Views/Examples/PayPerDownloadMulti.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Pay Per Download Multi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Pay Per Download Multi</h2>

<div align='center'>
    <div style='width:100%;height:auto;line-height:50px;background-color:#f1f1f1;border-bottom:1px solid #ddd;color:#49abe9;font-size:18px;'>
        4. Gourl <b>Pay-Per-Download</b> Example (multiple cryptocurrencies). Use it on your website.
        <div style='float: right;'>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html#p2'>View Source</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href=@Url.Action("PayPerDownload", "Examples")@Request.Url.Query.ToString()>Single Crypto</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html'>Other Examples</a>
        </div>
    </div>
    <h2>Example - Paid File Downloads (multi coins below)</h2>
    <br><h1>File: @ViewBag.filename</h1>
    Price: ~@Model.amountUSD US$<br>
    <a @Html.Raw(@ViewBag.DownloadLink)><img alt='Download File' border='0' src='https://gourl.io/images/zip.png'></a><br>
    <a @Html.Raw(@ViewBag.DownloadLink)>Download File</a>
@if (!Model.is_paid)
{
    @Html.CurrencyBox((string [])ViewBag.Coins, (string)ViewBag.DefCoin, (string)ViewBag.DefLang, 90, new {style="margin: 80px 0 0 0"})
}
else
{
    <br><br><br><br>
}
    <div style='margin:30px 0 5px 300px'>Language: &#160; @Html.LanguageBox()</div>
    @Html.Cryptobox(Model)


</div><br><br><br><br><br><br>
<div style='position:absolute;left:0;'><a target="_blank" href="http://validator.w3.org/check?uri=@HttpContext.Current.Request.Url.AbsoluteUri"><img src="https://gourl.io/images/w3c.png" alt="Valid HTML 4.01 Transitional"></a></div>

PayAltcoins/Gourl/Views/Examples/PayPerMembership.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Pay Per Multi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align='center'>
    <div style='width:100%;height:auto;line-height:50px;background-color:#f1f1f1;border-bottom:1px solid #ddd;color:#49abe9;font-size:18px;'>
        11. Gourl <b>Pay-Per-Membership</b> Example (@Model.coinName payments). Use it on your website.
        <div style='float: right;'>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://github.com/cryptoapi/Payment-Gateway/blob/master/Examples/pay-per-membership.php'>View Source</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href=@Url.Action("PayPerMembershipMulti", "Examples")@Request.Url.Query.ToString()>Multiple Crypto</a>
            <a style='font-size:15px;color:#389ad8;margin-right:20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html'>Other Examples</a>
        </div>
    </div>
    <br>
    <h1>Example - Upgrading to a Premium Account</h1>
    @if (Model.is_paid)
    {
        <!-- User already paid premium membership -->
        <!-- You can use this function - $box->is_paid() on all other your premium webpages, it will return true during all user paid period (1 month) -->
        <!-- Your Premium Pages Code Here -->
        <br>
        <br>
        <br>
        @ViewBag.Message
        <br>
        <br>
        <br>
    }
    else
    {
        <!-- Awaiting Payment -->
        <a href='#gourlcryptocoins'><img alt='Awaiting Payment - Cryptocoin Pay Per Membership' border='0' src='https://gourl.io/images/example10.png'></a>
        <br>
        <br>
        <br>
        <h3>Upgrade Your Membership Now ( $@Model.amountUSD per @Model.period ) - </h3>
    }

    <div style='font-size:12px;margin:50px 0 5px 370px'>Language: &#160; @Html.LanguageBox("en")</div>
    @Html.Cryptobox(Model, true, 540, 230, new {style = "padding:3px 6px;margin:10px;border:10px solid #f7f5f2;"})


</div><br><br><br><br><br><br>
<div style='position:absolute;left:0;'><a target="_blank" href="http://validator.w3.org/check?uri=@HttpContext.Current.Request.Url.AbsoluteUri"><img src="https://gourl.io/images/w3c.png" alt="Valid HTML 4.01 Transitional"></a></div>

PayAltcoins/Gourl/Views/Examples/PayPerMembershipMulti.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Pay Per Membership Multi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align='center'>
    <div style='width:100%;height:auto;line-height:50px;background-color:#f1f1f1;border-bottom:1px solid #ddd;color:#49abe9;font-size:18px;'>
        12. Gourl <b>Pay-Per-Membership</b> Example (multiple cryptocurrencies). Use it on your website.
        <div style='float: right;'>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html#p6'>View Source</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href=@Url.Action("PayPerMembership", "Examples" )@Request.Url.Query.ToString()>Single Crypto</a>
            <a style='font-size:15px;color:#389ad8;margin-right:20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html'>Other Examples</a>
        </div>
    </div>
    <br>
    <h1>Example - Upgrading to a Premium Account (multi coins below)</h1>
    @if (!Model.is_paid)
    {
        <!-- User already paid premium membership -->
        <!-- You can use this function - $box->is_paid() on all other your premium webpages, it will return true during all user paid period (1 month) -->
        <!-- Your Premium Pages Code Here -->
        <br>
        <br>
        <br>
        @ViewBag.Message
        <br>
        <br>
        <br>
    }
    else
    {
        <!-- Awaiting Payment -->
        <a href='#gourlcryptocoins'><img alt='Awaiting Payment - Cryptocoin Pay Per Membership' border='0' src='https://gourl.io/images/example10.png'></a>
        <br>
        <br>
        <br>
        <h3>Upgrade Your Membership Now ( $@Model.amountUSD per @Model.period ) - </h3>
    }

    <br><br>
    @if (!Model.is_paid)
    {
        @Html.CurrencyBox((string[]) ViewBag.Coins, (string) ViewBag.DefCoin, (string) ViewBag.DefLang, 60, new {style = "margin: 80px 0 0 0"})
    }
    <div style='font-size:12px;margin:50px 0 5px 370px'>Language: &#160; @Html.LanguageBox("en")</div>
    @Html.Cryptobox(Model, true, 540, 230, new {style = "padding:3px 6px;margin:10px;border:10px solid #f7f5f2;"})


</div><br><br><br><br><br><br>
<div style='position:absolute;left:0;'><a target="_blank" href="http://validator.w3.org/check?uri=@HttpContext.Current.Request.Url.AbsoluteUri"><img src="https://gourl.io/images/w3c.png" alt="Valid HTML 4.01 Transitional"></a></div>

PayAltcoins/Gourl/Views/Examples/PayPerPage.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Pay Per Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align='center'>
    <div style='width:100%;height:auto;line-height:50px;background-color:#f1f1f1;border-bottom:1px solid #ddd;color:#49abe9;font-size:18px;'>
        9. Gourl <b>Pay-Per-View/Page</b> Example (@Model.coinName payments). Use it on your website.
        <div style='float: right;'>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://github.com/cryptoapi/Payment-Gateway/blob/master/Examples/pay-per-page.php'>View Source</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href=@Url.Action("PayPerDownloadMulti", "Examples" )@Request.Url.Query.ToString()>Multiple Crypto</a>
            <a style='font-size:15px;color:#389ad8;margin-right:20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html'>Other Examples</a>
        </div>
    </div>
    <br>
    <h1>Example - Pay Per View - Video/Page Access for Unregistered Visitors</h1>
    <h3>Your Website Visitors have to pay for access to your premium video/webpage(s)</h3>
    <br>
    Price: ~@Model.amountUSD US$ for @Model.period access
    <br><br>
    @if (@Model.is_paid)
    {
        <!-- Successful Cryptocoin Payment received -->
        <!-- You can use the same payment gateway code for few your pages (section1) -->
        <!-- Your Premium Page(s) Code -->

        <h2 style='color: #339e2e;'>Cryptocoin Payment received<br>Successful Access to Premium Page (during @Model.period)
        </h2>
        <img alt='Cryptocoin Pay Per Page Access' border='0' src='https://gourl.io/images/example9_2.jpg'>
    }
    else
    {

        <!-- Awaiting Payment -->
        <img alt='Awaiting Payment - Cryptocoin Pay Per Page Access' border='0' src='https://gourl.io/images/example9.jpg'>
        <div style='font-size: 12px; margin: 30px 0 5px 370px'>Language: &#160; @Html.LanguageBox() </div>
        @Html.Cryptobox(Model, true, 540, 230, new {style = "padding:3px 6px;margin:10px"})
    }


</div><br><br><br><br><br><br>
<div style='position:absolute;left:0;'><a target="_blank" href="http://validator.w3.org/check?uri=@HttpContext.Current.Request.Url.AbsoluteUri"><img src="https://gourl.io/images/w3c.png" alt="Valid HTML 4.01 Transitional"></a></div>

PayAltcoins/Gourl/Views/Examples/PayPerPageMulti.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Pay Per Page Multi";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align='center'>
    <div style='width:100%;height:auto;line-height:50px;background-color:#f1f1f1;border-bottom:1px solid #ddd;color:#49abe9;font-size:18px;'>
        10. Gourl <b>Pay-Per-View/Page</b> Example (multiple cryptocurrencies). Use it on your website.
        <div style='float: right;'>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html#p5'>View Source</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href=@Url.Action("PayPerDownloadMulti", "Examples" )@Request.Url.Query.ToString()>Single Crypto</a>
            <a style='font-size:15px;color:#389ad8;margin-right:20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html'>Other Examples</a>
        </div>
    </div>
    <br>
    <h1>Example - Pay Per View - Video/Page Access for Unregistered Visitors (multi coins below)</h1>
    <h3>Your Website Visitors have to pay for access to your premium video/webpage(s)</h3>
    <br>
    Price: ~@Model.amountUSD US$ for @Model.period access
    <br><br>
    @if (@Model.is_paid)
    {

    <!-- Successful Cryptocoin Payment received -->
    <!-- You can use the same payment gateway code for few your pages (section1) -->
    <!-- Your Premium Page(s) Code -->

    <h2 style='color: #339e2e;'>
        Cryptocoin Payment received<br>Successful Access to Premium Page (during @Model.period)
    </h2>
    <img alt='Pay Per View Access' border='0' src='https://gourl.io/images/example9_2.jpg'>

    }
    else
    {

    <!-- Awaiting Payment -->
    <a href='#gourlcryptocoins'><img alt='Awaiting Payment - Pay Per View' border='0' src='https://gourl.io/images/example9.jpg'></a>
    <br>
    <br>
    <br>
    <br>
    if (!Model.is_paid)
    {
    @Html.CurrencyBox((string [])ViewBag.Coins, (string)ViewBag.DefCoin, (string)ViewBag.DefLang, 90, new {style="margin: 80px 0 0 0"})
    }
    <div style='font-size: 12px; margin: 30px 0 5px 370px'>Language: &#160; @Html.LanguageBox() </div>
    @Html.Cryptobox(Model, true, 540, 230, new {style = "padding:3px 6px;margin:10px"})

    }


</div><br><br><br><br><br><br>
<div style='position:absolute;left:0;'><a target="_blank" href="http://validator.w3.org/check?uri=@HttpContext.Current.Request.Url.AbsoluteUri"><img src="https://gourl.io/images/w3c.png" alt="Valid HTML 4.01 Transitional"></a></div>

PayAltcoins/Gourl/Views/Examples/PayPerPost.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Pay Per Post";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align='center'>
    <div style='width:100%;height:auto;line-height:50px;background-color:#f1f1f1;border-bottom:1px solid #ddd;color:#49abe9;font-size:18px;'>
        5. Gourl <b>Pay-Per-Post</b> Example (@Model.coinName payments). Use it on your website.
        <div style='float: right;'>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://github.com/cryptoapi/Payment-Gateway/blob/master/Examples/pay-per-post.php'>View Source</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href=@Url.Action("PayPerPostMulti", "Examples")@Request.Url.Query.ToString()>Multiple Crypto</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html'>Other Examples</a>
        </div>
    </div>
    <h1>Example - Paid Posts</h1>
    You can sell right to publish new posts on your website
    <br><br><br>
    <img alt='Invoice' border='0' src='https://gourl.io/images/example6.png'>
    <a name='i'></a>
    @if (ViewBag.successful)
    {

        <div align='center'>
            <img alt='New Post' border='0' src='https://gourl.io/images/example7.png'>
            <div style='margin: 40px; font-size: 24px; color: #339e2e; font-weight: bold'>Your text has been successfully posted on our website!</div>
            @Html.ActionLink("Publish new posts", "PayPerPost")
        </div>
    }
    else
    {
        using (Html.BeginForm("PayPerPost", "Examples", FormMethod.Post, new {style = "font-size: 14px; color: #444"}))
         {
             <table cellspacing='20'>
                 <tr><td colspan='2'><img alt='New Post' border='0' src='https://gourl.io/images/example7.png'>@Html.Raw(ViewBag.error)</td></tr>
                 <tr><td width='100'>Title: </td><td width='300'><input style='padding: 6px; font-size: 18px;' size='40' type="text" name="ftitle" value="@ViewBag.ftitle"></td></tr>
                 <tr><td>Text: </td><td><textarea style='padding: 6px; font-size: 18px;' rows="4" cols="40" name="ftext">@ViewBag.ftext</textarea></td></tr>
                 @if (!Model.is_paid)
                 {
                     <tr><td colspan='2'>@string.Format("* You need to pay {0}s (~{1} US$) for posting your text on our website", @Model.coinName, @Model.amountUSD)</td></tr>
                 }
             </table>
            <button type='submit' id='submit' style='padding: 6px 20px; font-size: 18px;'>Post Your Article/Comment</button>
            <div style='width: 600px; background-color: #f9f9f9; padding-top: 10px'>
                <div style='font-size: 12px; margin: 5px 0 5px 390px;'>Language: &#160; @Html.LanguageBox()</div>
                @Html.Cryptobox(Model)
            </div>
            <br>
            <br>
            <br>
         }
    }


</div><br><br><br><br><br><br>
<div style='position:absolute;left:0;'><a target="_blank" href="http://validator.w3.org/check?uri=@HttpContext.Current.Request.Url.AbsoluteUri"><img src="https://gourl.io/images/w3c.png" alt="Valid HTML 4.01 Transitional"></a></div>

PayAltcoins/Gourl/Views/Examples/PayPerProduct.cshtml
@using Gourl.GoUrlCore
@model Gourl.Models.GoUrl.DisplayCryptoboxModel

@{
    ViewBag.Title = "Pay Per Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div align='center'>
    <div style='width:100%;height:auto;line-height:50px;background-color:#f1f1f1;border-bottom:1px solid #ddd;color:#49abe9;font-size:18px;'>
        1. Gourl <b>Pay-Per-Product</b> Example (@Model.coinName payments). Use it on your website.
        <div style='float: right;'>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://github.com/cryptoapi/Payment-Gateway/blob/master/Examples/pay-per-product.php'>View Source</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href=@Url.Action("PayPerProductMulti", "Examples" )@Request.Url.Query.ToString()>Multiple Crypto</a>
            <a style='font-size: 15px; color: #389ad8; margin-right: 20px' href='https://gourl.io/@Model.coinName.ToLower()-payment-gateway-api.html'>Other Examples</a>
        </div>
    </div>
    <h1>Example - Customer Invoice</h1>
    <br>
    <img style='position:absolute;margin-left:auto;margin-right:auto;left:0;right:0;' alt='status' src='https://gourl.io/images/@(Model.is_paid?"paid":"unpaid").png'>
    <img alt='Invoice' border='0' height='500' src='https://gourl.io/images/invoice.png'>
    <br><br>
    @if (!Model.is_paid)
    {
    <h2>Pay Invoice Now - </h2>
    }
    else
    {
        <br><br>
    }
    <div style='margin: 30px 0 5px 300px'>Language: &#160; @Html.LanguageBox()</div>
    @Html.Cryptobox(Model, true, 580, 230)
    <br><br><br>
    <h3>Message :</h3>
    <h2 style='color:#999'>@Html.Raw(ViewBag.message)</h2>

</div><br><br><br><br><br><br>
<div style='position:absolute;left:0;'><a target="_blank" href="http://validator.w3.org/check?uri=@HttpContext.Current.Request.Url.AbsoluteUri"><img src="https://gourl.io/images/w3c.png" alt="Valid HTML 4.01 Transitional"></a></div>